version: '3.8'

services:
  nest_app:
    image: murshidmp/home_3d:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: "0.5"

# Remove the PostgreSQL service entirely